---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    accessKeyID: AgAgR3NgAE2gyJSScFgR9hkFHjCFkid5fhg6mrHP7jCMnywUoXd6zYp6cDJ5n7SErWMOV1fTJX3DR3UnARjMJX1NUP6Cn7/S2+ieyla78aUGCOOMwYLloyvbXLSP/zf6sdT8pmtqN4jLZDnVHGWoqnyuCDw51EUhh14l+uK9FvuNIdUh2dmWy9fuDA+01bacCNbYzgOy6ligwfSSCkW0TPI+Gr4nz49ZHVwoHcmVMSYqk0sJ+gbI2mDHU5d7Ae3UqKAAnnprqJnv2amCzdT7BSDZbaV2U0qkmWiR8l7EwTg7PFVeMNooBeEEngsA0Aq4d3/zzYI9SkCpLRcS3x1s26I5ciOuJ3ZF7TySyufZeeZo+kRR5Mc9l1NHQLQI1hmDfmI+xsRS+rDszB8JqWQrO4wZ/eDl7JHTF/yGmVmy3voKHHGiyf5DXLKG3PJKV07cTLsJLgjfVCymwWmYxLtm96pvTLLXvt+yAjirhW1MDtVaBEHe66vMBns5fX+SEFygF2EEWjoGm0GjiGvSeu9IVCUYFcmBQ+eqmLIWPvct/6Zxwxq97vjstV1+gOjA15mlmhHcwBhHvT8V3cxAkCXpsl2CfSNpuf2ote4lj09dHxgTf4GEzVzZgzVz7Vr6v/wvsqZEGDct34AYrZlAj21QG6sV49A/ixRDUmmWE2tH+0+Vku29or57fq70J6eTb1d+2JRJymPEqqLxZZiQBlNuJoStKHXbCQ==
    secretAccessKey: AgBTg7sWyja1KwgOSItr0ZXeNnUZV/DRbj3g3U1rvqBA2JbvbAuTCcIq0Ob+MVVapI0L8H037+Al6Kpsgp2NaNb4Mwn9Y3fLu1PzD15qdAbvw7t/1w+xZsD62MCQNYiMCNYl9chvnOdPekxbo10cnHfkAHOY82luL0q7AqwwfaH3YowniOwwSTjoNHrCTOu4hMQrwUBTB4VEfMu3Ds6q2O++dzeYWlbvxSxyz4t1IlBFm4w+Ojk7bulfPztf9lXlP87WLenc43abfq0yu6G6UgH2BLgSk5Ez0KIn1MKDglaaIYX+hGpqa1UnmdFF/C6F5fglya/CekzRdgR25OB/BplLtNsw3fKPwZsXi0x53k7Usierkcp41eOnTlxpN0LSao0c4Q07j4rw7xtqEXGli6+6s9lcrIq6lyMwlEjyd1Tws6V4/tty29172f3DiUnWf3ozpuhdLERB96ndNJBACC2ET1xBTDEitxHzb/R0IJaLxPaVDJhHHvqavgmTVWkE8vUbEkoQfJvUyxHOBg9nDlTsMmjemOMR7RBPbUxYpItibHdL5cku68hcHJN16tSapEKlQ9CuOD+nvJVq+vURsUANapzON2bGgOqCLtz8ehzi87S9sRIN/J405VaDWxJbIs25o3XUTH7oii5LIntvmATOPCdr9DbKRdNkNTlUa+R4HDnGScbICuhaC/hx6XHijijrP8O1AkwFR6JyrUO/T0k1xgTdqfl7622b6lfZ9WUJQGsU7svYpEbE
  template:
    metadata:
      name: route53-credentials
      namespace: cert-manager
    type: Opaque
