---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: heron-cookie
  namespace: heron
spec:
  encryptedData:
    cookie-secret: AgAubYpmhFXdGnaM7Ub8Z2jWTQCPA8BIcNOr+FUg0q96OFovnnWrQHwSCw0N+fPKUceLVYO67pEPrEVpi1fj5AjqY0wBo6vO2VrhXGiRGvAFV3ZkpEJIIf2kKuS+tBr1DycBTul6rH3X13RnWTEPJpmz3eJJ2B0BUbjnLgXu7lhuvAqGDT7qidPYxzeEef51LZhpGYhqKOPdpkASWcRXJWYQBMGn3RQ6CWIsxFn9QVLZyBywGsTBJUGo/BVJc+MnZAasgznhmuRfTlIwdOlmQlDAB2utSc57SBgF5n1pIXUVN/X7hA+fzDM3x6eaHIuqQFS1buZWYdTy9orOOX5wCTvxypsymQkgGAYLvT/O0BSFiJXErAjVdg0kMkYjuii0FVbLC6l1neQHwA0G+MRtRxPEtMsDqfjj3JNAE6yxrn6yd+fU9iS4Ioaj415m5gJrrAYHOZHA+E/gHjdYaprczgKvDmy6WzWiIC+h1H0lwENuWVrhchmx+ss2Hpfg8rhJn6Jrgc7ITloC6gVjzC2/0lONyhPFxwAdpoSYkNw+wurSI810XOqVk4z8HSFXNJ+ZNilsUtoInADOStOako3pT1NIu8oeRAtVozoSdHxpWsq6BbdMSLgkGKxD2eUSeRpiLNwtacJbXFR9tEIk5H90VvhLVvLbdcgQJQvxNBYEBrWcRmoLhOxkT8SmarTPbKqCL0AMg/aAU3ykJaqqZFSwLa89ueL+TIOP1sW8WmdAYSS4lUVTQOnBwTyqkNk0rA==
  template:
    metadata:
      name: heron-cookie
      namespace: heron
