---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp
  namespace: openshift-monitoring
spec:
  encryptedData:
    password: AgAheGyQ5AVOwd12If/QHvwEiAGFCYDPZ1PMmKRAfaN0YDwPEHE7RYxkOL1Eo4W9mUZS1iRdd10TW0fqY6ik0sPs/2HridiUgDgOXOFcbB8cCTmNzFvO4zY1dkxALW7p9bioponWyX879+OvHgRoAiVzGUTCv6S31XrtZWdXMA0MBsLl5/jTI1oDm1DKjXphqpZlOK9FGPk5BCjxSHTjzRl+fakSY7fN0Po28iu0wbUG7QUyZRkDLsofnzngG+zpS9I8zf+yuFH0raHwukEVP9cqklIzfU2CBAKuzXWZNjfxadyFbX+Vg7wRKsvdZIgnT+NrAWpaBj5nrHe7X3wyuHk8dU4TjhAFZ/7/9RvLdNYPizUvHhkMkPWIgVRolME2nhTtUN+F5lqUg/ezJQX4QlJQDI8e5WEth/SkEKo+BcrhWS1laqLiJys/C3jq2apYQMDY6zsAfBaJFYfUzxgjgad0Q1SgPIkcmcceMbG9xy0gmINDiDUfrS3bXqr6qcuCewTBfc2WkSXMjHm0rbrXs0mzN8X9YjwjvlrklZOephZrCf+H4bf6uSePAiCRPJp+KMezfyvLDnxfgxNXx/4aqFiG0qvt27Lrd9uJ2K0soC3M+QCYsdUm+mLKw+ndp7fMHBtWXktf3l6BmiCuDCCXh0jrq+13y5hlZAzMRnxnBckNpG0X3napdBV4WQ1Jh/qgyLlkHHISRlXM++c4aZ4jU71c
  template:
    metadata:
      name: alertmanager-smtp
      namespace: openshift-monitoring
    type: Opaque
