apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-timemachine
  namespace: samba
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 1Ti
