apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-credentials
  namespace: openshift-adp
spec:
  encryptedData:
    cloud: AgBuXp6AmnONfQic/feIBCoNFQNOZHIQNo2X1SozDewb9nqhVD55IIublDI4zR4TnlqvUIFY7dOdPMykafkjCHKu/Ana74bzGKkX+QT/eEdf90n63I42r8/EBj53hmO3MhR4okJ+2LqSGLmz3+E/RLtdBQB2KF+DhL+3O/T8gQW46lucIa7oKY9X8J/iWuKesbc5QJax/3kxvBoGnFjgAKtKeophp7dpv4Oae5TvEpQjUtl3pz/mjk+ZCmwcUutEsgSuB9VAO5YAmxtsabJa/GfLn6Lx3ZZXlxV6VRO66b0GLJpICN1pr1/ZHhatGjnJkU2elOhK2rfuFlZ1O5kJraGl0tNR/TNjwuhEMfUbpP7vSdah2uMhak6sAGpWEJgT0rMnzRRNGnx8n/FwG2EL94fiNqAdv8YEu/4qkAd/cCBawNrWnDPTNuBRu9gJWE+hSyDCh/vK3rvp+2mZIxp8U7McrM8rt9GbJLuWTEr1PFbZkEI9opc1cBssZ4uz9+IIdtfw2dSAoal2i7+tn7z9CaoxswDNEZ/A+MDi26Niu0shK7+/XGM2U1Nulcs7EDE9pdq+Gy5Iw2JeKGZIx1CM5EvFjNsl/rroFnNClskX1/ODS/FH7S879mPbWHKyWCnMF4aGXkMWBuYwXGONqn9FosVTFYaxFoEvjAlONJat9TXVon0mhGRuL88UK4A3HOqJ+RiaJno0IUrViDzQTvxt/qKthN4SvIH6yyHgYODLp6HCS6zEqhq6kAY0YFVomBDLm8YJ/psRjHEP9HcwAPPqmUjgVfho1BbE7jvyLM6oTmTp2l889ZbiB1abb9eBXVDD+40HHN009c/gfmyvSERAwHV/lh3X
  template:
    metadata:
      name: cloud-credentials
      namespace: openshift-adp
