apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: dharmabruce-daily
  namespace: openshift-adp
spec:
  schedule: "0 2 * * *"
  template:
    includedNamespaces:
      - dharmabruce
    storageLocation: default
    ttl: 168h0m0s
