apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: fred-vaughan-cc-daily
  namespace: openshift-adp
spec:
  schedule: "0 2 * * *"
  template:
    includedNamespaces:
      - fred-vaughan-cc
    storageLocation: default
    ttl: 168h0m0s
