apiVersion: v1
data:
  LOG_LEVEL: info
  ansibleIntegration: disabled
  singleNodeOpenshift: disabled
kind: ConfigMap
metadata:
  annotations:
    installer.open-cluster-management.io/release-version: "2.16.2"
  labels:
    app: console
    chart: console-chart-2.16.2
    component: console
    installer.name: multiclusterhub
    installer.namespace: open-cluster-management
    release: console-chart
  name: console-config
  namespace: open-cluster-management
