apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: ["configmaps-console-config.yaml", "configmaps-manager-config.yaml", "configmaps-search-v2-operator-manager-config.yaml", "rolebindings-console-metrics-monitor.yaml", "roles-console-metrics-monitor.yaml"]
