---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: samba-credentials
  namespace: samba
spec:
  encryptedData:
    password: AgA5O1SJIiN9RUoZhaynoqo7huS9G4CMWF8TWlSm7v69tYRXQKLVcaeSG3PbFZrlWIjLgNJfvcyZbT+MdSUOGgwAJ+L+6nCMU5JeNxJAeqNE1pe2pMg47UefmyjZBZjzCPZTzjeRGqM4Gnnb2lSHbgdLVWQAGnx/0T54HPmQdVsY9sHchu808u0i5xWQ/L6l9MK+NuWloRSleP4Hvu6uMUobkcsLZU5hhmixMMLwlS0SGtkE6JV5tdM1SG52JvZRLK5A+K/d9trplFTfhgcVFu4vY39zIEs+3SMnmNo9SYl333nxQyZJiOGfSB9K7CXmTNDt+mQwIN45mHsyjf8+j5BNuUBZi4ZDch3TBSBNE/CDaVs3BSlLM52Eh9vBQ5RGiWh4Pg1VNHThA8RJJF09lxvSMkJJrIS6la7SQWFywiipscv3XH5PTxG31agSBS2WKizu/Z00rB8k17QxfV8DUtc6GJ+JwliH1RRuKdtenwEOS7+9mGifqLj3y/whwLrpFqSLnsUurS6lmvZCAXcgOKrV2rrqVh58gRjvSa4pTKKbA3R9vJijL2Mq6flhRDvMC0LuEovZMe3yF6ES5OMP0N9K0XtscRne9E0bJS5Ljo/opS+AToN1bbgRkFq2u2vYq1Mb7Ecm18LQfoNQEpETus7J1+O+zD6sTuekbH6jD/33ID8tvmblh9e/hcaP4FV8Lp51Bthz2S5U9pQMdM7De6LRuOj944nNouIchBSFVL03ch047pyEsdfruQ+SckO2Vug=
  template:
    metadata:
      name: samba-credentials
      namespace: samba
