---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: samba-credentials
  namespace: samba
spec:
  encryptedData:
    password: AgBELSU6aiSInMxs2lg1ZXia8QGvgfp5ob5bdnZY26usT1JDwL2WBAzgYEtqJra8e0Pene0cR8Neilx7JcX1vYo6Ea/I/Lfz0BXjD/slBpAk3luODkd5UuUzx40WaJVO43jla8DJGtlqf6Uj2ZKpeAwk9ZkGben2wRvJypssIKyEAal37NGsTLfsu52hIyXeHQHx9kK6oprbz7UoXL32eu+8fj2GQPoKLzv+CA4auxA8A4uyqOhtDShR5PyOZMKLVkCU3dOEmB3wbaGyNriR2dCUYIR54i3ETe5RfJcoQD7jCu92URHgYyl/iLXRIF8ZFBm8hA28I7qvzekqoQbZsK9uIkb7pMMLXA9M+zocuN+CXOgNWQ8UwC0Lhf00j4O1/ydGF94T63Eg0TNEtRRixEqEDKTaOm30NSXDAQsfmtVTrIJ2TSnFnxH4NN5H7S1hSHiOuriM/a4X/SMx4US14QD5d8uZEeQCjia1gGSGutuQUnSVWXIKNJoH0kmfttzrWqV7AjC4M5u62jib+ejkSzz5Ro4j+tgwa0Fby/rGz+4J0OHIytifczpjlFpduoiXmrBNnmfkiQNk9l3d4Q+nWs2/x/GYF3iwVFBszt67bT0OFEyvcwK7Mgtoa4TDPUsarwyN+HTegbiXETfGNranJjkNKdMrFGKVFp3oP8uBJNMHnd49qaCp8arn93ZYXe5xSVzdsd+D39bH4YsKdCdUvhpZm6A0sOUPKOKro117kgY5qA==
  template:
    metadata:
      name: samba-credentials
      namespace: samba
