---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fred-smtp
  namespace: fred-vaughan-cc
spec:
  encryptedData:
    password: AgC5idYQn7HaDk7A19v2IRFFKGjzn5VxJJbQ6C8cjFWtKAM3o91Nuchw4TEAc+JHTf4aoj3/lvEwqJAa+5qB7uGAL6hcdDyBVL6NAXb/UeTRVb4ybrKh5D9lhIWazNNYcvAD+4WjHmJ9D2TVn5HfnvVYDr9cKEK/7P5zUAd5wi8HWb6p/KKEPFlLGn9br4s3jJITlivOvrrLkM702nu/Jp/LUZIvl42ajMaVRe8/I0RJBlvxP/+OJcFiPolCtdZUEkXUkPosIWYQo2DA/lsff450h/cNSlcgmh41ycx+uXrM/17LYTf/MeELpUr4+DrM9YDlDW+9lHKWgKnpOSmRhCN2XpVcahvpcgcHmT5VZV615ulz3nCI10US05UH99riLWRCne7Ku9nFZmUliF8M4HhrqBgYa8EqrtFdIXi/TWSUODV/mu0go4qO4ekq+wjbUh53pc/fud38cborj+i/QVj0CzJzA2XnD2DMLymAM6XTHfoyRrSLslYFd6DlYhdbVkzuZezd1iaV7TZ0BfQsrjXdIMRJ9CsHdwphqcRRoEHqyyy4x1YrPjYeVNcCVI4YnUgK+57wiNoPDDHsUIr6HFKbRD6j80ApRe8ZXurBlm3xm7dyw98uIHo51bVR3nhxIMNjsDrcIN9AZhqFXmSYJPNQmm+m+oEiD2hpur3zJ09gfi7ftZ4w9j9Y0i7UBhf0T8yKGW+BfUvVvG4Crw5gWUgE
  template:
    metadata:
      name: fred-smtp
      namespace: fred-vaughan-cc
    type: Opaque
