---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-data
  namespace: heron
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 5Gi
