apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: ["configmaps-gitlab-nginx-ingress-tcp.yaml", "rolebindings-gitlab-anyuid-hostports.yaml", "rolebindings-gitlab-nonroot-v2.yaml", "rolebindings-nginx-controller-scc.yaml"]
