# Sealed against k8s-sno's sealed-secrets key. To rotate, update
# clusters/k8s-sno/openshift-authentication/google-client-secret.yaml and re-run kubeseal.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-oauth-client-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgBwwOYV3ldrmhUSsowTNHcaErt/e4Y7DrcxvEfUOQgiZflVzIUlOdHSCF460FHskFlOkchq/wL+omXCto3QkCufdrowClB6vK8xpp9Xm0EGIe6m29Abl8lfXcWa9kOPWuXvC0cwB/inOy6z+fiesEwtdHkGxPArXh1L4SXtLMlD5aeCJgoXyUCW0aFZHgcoo6F5k7nKBHJT/+gnRzm6jr+sU8ewous/1eGYQV+zDjybZb8/knLk7ee0SJ2zqtZ9Re5daL+TVNz+UMjPCE9/0k7h3vdi24SFE6R4m3vDx+v4yYW7IdXDjv/DuX/NGWEjVG1J0pNXyVcneKlVudvzqp0cUuFKQL8szTUrqNDwKnJN4e3+W/hge+4v5zLNWISrhKxdKcM8gUIt6wP4sHG2nQw1iIiSA0BaGeaTQmyKZR7ZcWxCjb3G7ibg4LI+BnA7Q5Kfr8GquN/goXSajGb98O+UN5lxXvnqeQOnu8iq7m1h707aNIKPgF6ZEueFc4OnCyMOQnhElRYaU6DXKoUKnySSlm8oP6gTQmvFg/f73ii99R01rBd1A7C1h2VF166jZdiKDJEJUG3mGhGOSVuOFSwHYGGE3JZnSwJC+Z1ieNuXg4dwQW7++NcQHSSpniz87TaRluVgzd9yOumQZJEFIcx8UxGuxeHC6Z0p263YnbZB9vC59GwtQ9Jz/lnOX3u6b4YGGjEPMRWmem0WJrmYpeiDHfgVmhF2GnREzLkBhbMJ/+3lfg==
  template:
    metadata:
      name: google-oauth-client-secret
      namespace: openshift-config
    type: Opaque
