apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: ["configmaps-feature-gate.yaml", "configmaps-supported-versions.yaml", "rolebindings-prometheus.yaml", "roles-prometheus.yaml"]
