apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mountainheart-net

resources:
  - namespace.yaml
  - service-account.yaml
  - certificate.yaml
  - router-cert-role.yaml
  - router-cert-role-binding.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
