apiVersion: v1
data:
  heritage: "[{\"containerID\":\"d73663d6064a\",\"podIP\":\"10.128.0.63\",\"sensorStart\":\"2026-03-04T00:02:19.87588628Z\",\"sensorVersion\":\"4.10.0\"},{\"containerID\":\"191c735d198d\",\"podIP\":\"10.128.0.198\",\"sensorStart\":\"2026-02-20T20:55:59.689669599Z\",\"sensorVersion\":\"4.9.3\"}]"
kind: ConfigMap
metadata:
  annotations:
    stackrox.io/past-sensors-info: "This data is for sensor to recognize its past pod instances."
  labels:
    app.kubernetes.io/created-by: sensor
    app.kubernetes.io/managed-by: sensor
    app.kubernetes.io/name: sensor
    auto-upgrade.stackrox.io/component: sensor
    auto-upgrade.stackrox.io/preserve-resources: "true"
  name: sensor-past-instances
  namespace: stackrox
