apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: "{\"holderIdentity\":\"external-secrets-operator-controller-manager-7db8c7f997-8w6k4_541a926b-f1ff-428e-bf64-840041a7cfaa\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2025-10-28T17:27:58Z\",\"renewTime\":\"2025-10-28T17:54:29Z\",\"leaderTransitions\":0}"
  name: external-secrets-operator
  namespace: external-secrets
