apiVersion: v1
data:
  ca-cert-path: ""
  check-cluster-version: "true"
  cluster-id: "95afe0b5-c4b2-490e-b021-908f4c544d5f"
  control-plane-count: "1"
  inventory-url: "https://api.openshift.com"
  must-gather-image: "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0cc6d999e5e52bfe425b80493657ffd973e8d8729faf520d2217e6ccef6c08ca"
  skip-cert-verification: "false"
kind: ConfigMap
metadata:
  labels:
    app: assisted-installer-controller
  name: assisted-installer-controller-config
  namespace: assisted-installer
